builders:
  - script
slack:
  room: "eduid-builds"
clean_workspace: true
publish_over_ssh:
  - pypi.sunet.se

script:
  - "python3.7 -m venv venv"
  - ". venv/bin/activate"
  - "pip install --upgrade setuptools pip wheel mypy"
  - "python setup.py testing"
  - "pytest"
  - "mypy --ignore-missing-imports src/vccs_client"
  - "python setup.py sdist bdist_wheel --universal"

